djangoapps/urls.py
from django.contrib import admin
from django.urls import path, re_path

from baseball import views as baseball_vw

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', baseball_vw.project_markdown),
    # re_path(r'^runJobs/', baseball_vw.run_jobs_view),
    re_path(r'^viewStats/', baseball_vw.stats_view),
    re_path(r'^project/', baseball_vw.project_markdown),
    re_path(r'^jobs-dashboard/', baseball_vw.jobs_dashboard),
    re_path(r'ajax/load-teams/', baseball_vw.load_teams, name='ajax_load_teams'),
    re_path(r'api/stat_results', baseball_vw.StatsResults.as_view(), name='api_get_stats'),
    re_path(r'flowchart/', baseball_vw.process_flowchart)
]

baseball/models.py
from django.db import models
from .oper import date_time as dt

# CHOICES
WHICH_TEAM = [('away', 0), ('home', 1)]
PLAY_TYPE = [('play', 'play'), ('sub', 'sub')]
STAT_CATEGORY = [('batting', 0), ('pitching', 1), ('defense', 2)]

# constants
YEARS = dt.gen_year()
TEAMS = (('ANA', 'ANA'), ('ARI', 'ARI'), ('ATL', 'ATL'), ('BAL', 'BAL'), ('BOS', 'BOS'), ('CHA', 'CHA'),
         ('CHN', 'CHN'), ('CIN', 'CIN'), ('CLE', 'CLE'), ('COL', 'COL'), ('DET', 'DET'), ('HOU', 'HOU'),
         ('KCA', 'KCA'), ('LAN', 'LAN'), ('MIA', 'MIA'), ('MIL', 'MIL'), ('MIN', 'MIN'), ('NYA', 'NYA'),
         ('NYN', 'NYN'), ('OAK', 'OAK'), ('PHI', 'PHI'), ('PIT', 'PIT'), ('SDN', 'SDN'), ('SEA', 'SEA'),
         ('SFN', 'SFN'), ('SLN', 'SLN'), ('TBA', 'TBA'), ('TEX', 'TEX'), ('TOR', 'TOR'), ('WAS', 'WAS'))
FORM_TYPE = (('import_year', 'import_year'), ('process_team', 'process_team'), ('generate_stats', 'generate_stats'),
             ('view_stats', 'view_stats'))


# Extract/Process Requests
class JobRequirements(models.Model):
    year = models.IntegerField(choices=YEARS)
    team = models.CharField(max_length=4, choices=TEAMS)
    form_type = models.CharField(max_length=20, choices=FORM_TYPE, null=True, default=None)

    def __str__(self):
        return str(self.year) + str(self.team) + str(self.form_type)


# Teams
class Team(models.Model):
    team_id = models.CharField(max_length=15)
    team_city = models.CharField(max_length=25)
    team_name = models.CharField(max_length=15)

    def __str__(self):
        return self.team_name


# Game Info
class GameInfo(models.Model):
    game_id = models.CharField(max_length=12)
    home_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='_home_team')
    away_team = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, related_name='_away_team')
    game_info = models.CharField(max_length=100)

    def __str__(self):
        return self.game_id


# Players
class Player(models.Model):
    player_id = models.CharField(max_length=10)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=25)

    def __str__(self):
        return self.player_id


# Starters
class Starter(models.Model):
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    away_1 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_1')
    away_2 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_2')
    away_3 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_3')
    away_4 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_4')
    away_5 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_5')
    away_6 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_6')
    away_7 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_7')
    away_8 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_8')
    away_9 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_9')
    away_10 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_away_10')
    home_1 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_1')
    home_2 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_2')
    home_3 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_3')
    home_4 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_4')
    home_5 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_5')
    home_6 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_6')
    home_7 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_7')
    home_8 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_8')
    home_9 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_9')
    home_10 = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_home_10')

    def __str__(self):
        return self.game_id


# Game Plays
class GamePlay(models.Model):
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    type_of_play = models.CharField(max_length=4, choices=PLAY_TYPE)
    inning = models.IntegerField()
    which_half = models.IntegerField(choices=WHICH_TEAM)
    half_innings = models.CharField(max_length=4)
    player_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_player')
    pitch_count = models.CharField(max_length=2)
    pitches = models.CharField(max_length=30)
    the_play = models.CharField(max_length=40)
    # player_name -- does this need reference?
    which_team = models.IntegerField(choices=WHICH_TEAM)
    team_name = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL)
    batting_spot = models.IntegerField()
    fielding_pos = models.IntegerField()
    pitcher_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL, related_name='_pitcher')
    num_of_outs = models.IntegerField()
    before_1b = models.CharField(max_length=12)
    before_2b = models.CharField(max_length=12)
    before_3b = models.CharField(max_length=12)
    after_1b = models.CharField(max_length=12)
    after_2b = models.CharField(max_length=12)
    after_3b = models.CharField(max_length=12)
    runs_scored = models.IntegerField()
    total_scored = models.IntegerField()

    def __str__(self):
        return self.game_id + ': ' + self.half_inning + ' - ' + self.the_play


# Stat Collector
class StatCollect(models.Model):
    player_id = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    team_name = models.CharField(max_length=3)
    game_id = models.ForeignKey(GameInfo, null=True, on_delete=models.SET_NULL)
    half_inning = models.CharField(max_length=4)
    stat_type = models.CharField(max_length=5)
    stat_value = models.IntegerField()
    actual_play = models.CharField(max_length=40)
    num_of_outs = models.IntegerField()
    bases_taken = models.CharField(max_length=3)
    stat_team = models.IntegerField(choices=WHICH_TEAM)
    stat_category = models.CharField(max_length=8, choices=STAT_CATEGORY)

    def __str__(self):
        return player_id + ' stat for ' + stat_type + ': ' + stat_value

baseball/views.py
from django.shortcuts import render
from django.forms.models import model_to_dict
import json
from flask import jsonify
from django.core.serializers.json import DjangoJSONEncoder
from .models import StatCollect, JobRequirements
from .oper import db_setup as dbs
from .oper import check_latest_imports as chk
from .oper import database_reader as dr
from .oper import class_structure as cs
from .oper import global_variables as gv
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# from .apps import baseball
from .forms import GetYear, ProcessTeam, GenerateStats, ViewStats
from django.contrib import messages
from .functions import instantiate_forms
from djangoapps.utils import get_this_template
from datetime import time

'''
API Section
'''
from rest_framework import views
from rest_framework.response import Response
from .serializers import BatStatSerializer, PitchStatSerializer, FieldStatSerializer


# API View for getting Stats Results table
class StatsResults(views.APIView):

    # get request
    def get(self, request):

        # get cols and pop the columns not being displayed
        if request.GET['stats_table'] == 'batting':
            viewer_col = gv.bat_stat_types.copy()
        elif request.GET['stats_table'] == 'pitching':
            viewer_col = gv.pitch_stat_types.copy()
        elif request.GET['stats_table'] == 'fielding':
            viewer_col = gv.field_stat_types.copy()
        else:
            viewer_col = gv.bat_stat_types.copy()  # default batting for now
        viewer_col.pop('PID')
        viewer_col.pop('YEAR')

        # get the keys and values, then add in name to the viewer_col
        query_col = ['player_nm'] + list(viewer_col.values())
        post_col_keys = ['NAME'] + list(viewer_col.keys())
        viewer_col['NAME'] = 'player_nm'  # this way the order for will remain the same

        # read from database; || is concatenate in sqlite!
        # print(request.GET)
        query = "SELECT DISTINCT {} FROM "\
                    .format(", ".join(query_col).replace("team_name", "pyts.team_name")
                            .replace("player_nm", "(first_name || ' ' || last_name) as player_nm")) + \
                str(request.GET['stats_table']) + " b " + \
                "JOIN player_year_team pyts ON b.pyts_id = pyts.Id JOIN players p ON " + \
                "pyts.player_id=p.player_id AND pyts.team_name = p.team_id AND pyts.data_year = p.data_year " + \
                "WHERE pyts.team_name='{}' AND pyts.data_year={} " \
                    .format(str(request.GET['team']), str(request.GET['year']))
        # print(query)
        temp = dr.baseball_db_reader(query)
        # print(temp)

        # because `temp` is NOT a dictionary we need to convert it!
        post_col = post_col_keys
        results = []
        for t in temp:
            add = dict(zip(post_col, t))
            add['NAME'] = add['NAME'].replace('"', '')  # replace the extra '"' if there.
            results.append(add)

        # run thru the corresponding serializer
        if request.GET['stats_table'] == 'batting':
            data_output = BatStatSerializer(results, many=True).data
        elif request.GET['stats_table'] == 'pitching':
            data_output = PitchStatSerializer(results, many=True).data
        elif request.GET['stats_table'] == 'fielding':
            data_output = FieldStatSerializer(results, many=True).data
        else:
            data_output = BatStatSerializer(results, many=True).data

        return Response(data_output)


# home page
def home_page(request):
    return render(request, 'pages/homepage.html')


# project page
def project_markdown(request):

    page_height = 1050
    f = open('baseball/README.md', 'r')
    if f.mode == 'r':
        readme = f.read()
        page_height = len(readme)/2 + 200

    content = {
        'readme': readme,
        'page_height': page_height
    }

    template_page = get_this_template('baseball', 'project.html')

    return render(request, template_page, content)


# load drop-down teams based on year
def load_teams(request):

    # request.GET['year'] and request.GET.get('year') work the same?
    # print("Load GET YEAR: ", request.GET['year'])
    year = request.GET['year']
    teams = chk.get_team_choices2(year)
    # print("Load Teams: ", teams)
    team_choices = [r for (r, r) in teams]  # break the tuple
    # print("Load Teams View: ", team_choices)

    return render(request, 'partials/teams_dropdown_options.html', {'teams': team_choices})


# view stats
def stats_view(request):

    # get the year and team choices then grab the ViewStats Form
    year_choices = chk.get_year_choices2()
    # team_choices = [('---', '---')]  ## remove
    team_choices = chk.get_team_choices2("2019")
    form_view_stats = ViewStats(year_choices, team_choices, initial={'form_type': 'view_stats'})

    # process all columns and send it out
    col_types = {'batting': gv.bat_stat_types, 'pitching': gv.pitch_stat_types, 'fielding': gv.field_stat_types}
    all_cols = dict()
    for k, ct in enumerate(col_types):
        viewer_col = col_types[ct].copy()
        viewer_col.pop('PID')
        viewer_col.pop('YEAR')

        # get the keys and values, then add in name to the viewer_col
        query_col = ['player_nm'] + list(viewer_col.values())
        post_col_keys = ['NAME'] + list(viewer_col.keys())

        # change columns into ajax format for the DataTable.js
        ajax_col = []
        for col in post_col_keys:
            ac = {'data': col, 'title': col}
            ajax_col.append(ac)

        # query_col -- dict of post_col vs column desc
        query_col = [q.replace('_', ' ') for q in query_col]
        col_dict = dict(zip(post_col_keys, query_col))

        ct_dict = {
            'column_name': ajax_col,
            'column_desc': col_dict
        }

        all_cols[ct] = ct_dict

    # change heading
    heading = "Batting Stats for ANA in 2019"

    context = {
        'form_view_stats': form_view_stats,
        'col_types': all_cols
    }

    return render(request, 'pages/viewStats.html', context)


# run jobs View -- REMOVED 20200522


# this will replace the runJobs with a dashboard of the automated jobs
def jobs_dashboard(request):

    # the main 3 processes
    processes = [{'p': 'import_year'}, {'p': 'play_processor'}, {'p': 'stat_processor'}]

    # get column names of process_log table
    process_col = []
    cols = cs.process_log.columns
    for i in cols:
        process_col.append(str(i).replace('process_log.', ''))

    # years that have been imported
    query = "SELECT * FROM process_log WHERE process_name='import_year'"
    results = dr.baseball_db_reader(query)

    # for each row (tuple), sort and add columns
    years_imported = []
    for r in results:
        years_imported.append(dict(zip(process_col, r)))

    # for each year imported, check number of teams in total
    all_years = chk.get_years()
    all_years.sort()
    all_years.reverse()
    num_teams_array = []
    for y in all_years:
        num_teams = chk.check_teams(str(y), 'total_num_teams')
        num_teams_array.append({'data_year': y, 'num_teams': num_teams})

    # teams that have been processed -- by year
    query = "SELECT data_year, COUNT(team_name) FROM process_log WHERE process_name='play_processor' "
    query += "GROUP BY data_year ORDER BY data_year desc"
    results = dr.baseball_db_reader(query)

    # for each row (tuple), sort and add columns
    teams_processed = []
    for r in results:
        teams_processed.append(dict(zip(['data_year', 'num_teams'], r)))

    # go thru and divide teams/processed by total num of teams
    for n in num_teams_array:
        year = int(n['data_year'])
        num_teams = n['num_teams']
        for t in teams_processed:
            if t['data_year'] == year:
                t['num_teams'] = t['num_teams'] / num_teams
                # print(t)
                break

    if len(num_teams_array) > len(teams_processed):
        missing_years = len(num_teams_array) - len(teams_processed)
        len_index = len(num_teams_array) - 1
        for m in reversed(range(missing_years)):
            num_teams_array[len_index-m]['num_teams'] = 0
            teams_processed.append(num_teams_array[len_index-m])
    # print(teams_processed)

    # teams that have stats generated -- by year
    query = "SELECT data_year, COUNT(process_name) FROM process_log WHERE process_name LIKE 'stat_processor%' "
    query += "GROUP BY data_year ORDER BY data_year desc"
    results = dr.baseball_db_reader(query)

    # for each row (tuple), sort and add columns
    stats_generated = []
    for r in results:
        stats_generated.append(dict(zip(['data_year', 'processes'], r)))

    # go thru and divide teams/processed by total num of teams
    done_years = []
    stat_cats = ['batting', 'fielding', 'pitching']
    for s in stats_generated:
        year = s['data_year']
        if int(s['data_year']) == year:
            for n in stat_cats:
                s['processes'] = s['processes'] / (num_teams * len(stat_cats))
                # also check if the year is completed
                if s['processes'] == 1:
                    done_years.append(year)
                # print(t)
                break

    # IF FULLY COMPLETED -- merge them together!
    # first drop the completed
    for i, st in reversed(list(enumerate(stats_generated))):
        # if it's done year, drop it
        if st['processes'] == 1:
            stats_generated.pop(i)
    # print(stats_generated)
    # then add the completed, merged together, to top of the list
    stats_generated = [{
        'data_year': str(min(done_years)) + '-' + str(max(done_years)),
        'num_teams': 1
    }] + stats_generated

    # adjust the SAME done_years for the teams_processed
    # print(teams_processed)
    for i, st in reversed(list(enumerate(teams_processed))):
        # if it's done year, drop it

baseball/templates/pages/analyzeStats.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>View Team Stats</h1>
    </div><br>

    {% load crispy_forms_tags %}
    <!--form id="view_stats" action="" method="post" data-teams-url="{% url 'ajax_load_teams' %}" novalidate>
        {% csrf_token %}
        {{ form_view_stats.as_table }}
        <input type="submit" value="View Stats">
    </form>

    <div id="selected" class="d-flex justify-content-center">
        <h3>{{ heading }}</h3>
    </div><br>
    <div id="table_output" class="d-flex justify-content-center"></div>

    <script>
        (function () {
            window.results = JSON.parse('{{results|safe}}');
            window.columns = {{post_col|safe}};
            window.bat_col = JSON.parse('{{col_convert|safe}}');
        }());
    </script-->
    {% load static %}
    <!--script src="{% static 'scripts/baseball_view_stats.js' %}"></script-->
    <br>

    <!--script>
    // for the teams drop-down dependency
    $("#id_year").change(function () {
        var url = $("#view_stats").attr("data-teams-url");  // get the url of the `load_teams` view
        var yearId = $(this).val();  // get selected YEAR
        console.log(url);
        // initialize an AJAX request
        $.ajax({
            //async: true,
            url: url,  // set the url of the request (= localhost:8000/ajax/load-teams/)
            data: {
                'year': yearId  // add the year id to the GET parameters
            },
            success: function (data) {  // `data` is the return of the `load_teams` view function
                console.log(data);
                $("#id_team").html(data);  // replace with the values retrieved
            }
        });
    });
    </script-->

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/flowchart.html
{% include 'partials/header_mermaid.html' %}


    <div id="my_title" class="d-flex justify-content-center">
        <h1>Baseball Project Flowchart</h1>
    </div><br>
    <div class="mermaid">
        graph TB
            subgraph importYear
                S1[Start] --> A1[Get all files]
                A1 --> A2[Sort into Folder]
                A2 --> A3[Finish]
            end

            subgraph extractNames
                A3 --> S2
                S2[Start] --> B1[Extract Team Names]
                B1 --> B2[Extract all Player Names]
                B2 --> B3[Sort Both into Database]
                B3 --> B4[Finish]
            end

            subgraph processTeam
                B4 --> S3
                S3[Start] --> C[Loop thru file]
                C --> C1{If End of File}
                C1 --> |Yes|FN[Finish]
                C1 --> |No|D{Type of Play}
                D -->|Non-Plate Appearance| E1[Process Play]
                D -->|Plate Appearance| E2[Process Play]
                D -->|Substitution| E3[Handle Substitute]
                E2 --> E4[Handle Batter]
                E1 --> F[Record Raw Stats]
                E4 --> F
                E3 --> F
                F --> F1[Move Baserunners]
                F1 --> F2[Handle Current Half Inning]
                F2 --> |Next play|C
            end

            subgraph generateStats
                FN --> S4
                S4[Start] --> G1{Type of Stat}
                G1 --> |Batting|G3[Grab Raw Stats]
                G1 --> |Pitching|G3
                G1 --> |Fielding|G3
                G3 --> G4[Aggregate & Tally]
                G4 --> G5[Insert to Database]
                G5 --> H{If Test Case Exists}
                H --> |Yes|H1[Run Test Cases]
                H --> |No|H2[Finish]
            end
    </div>
    <br>
    <script>mermaid.initialize({startOnLoad:true});</script>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/homepage.html
{% include 'partials/header_baseball.html' %}
    <h1>Welcome</h1>
    <div id="startContent" class="container-fluid">

    <p>Edit this page later...</p>
    </div>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/jobsDashboard.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>Jobs Dashboard</h1>
    </div><br>

    <div id="startContent" class="d-flex justify-content-center">


    </div><br>

    <script>
        (function () {
                window.processes = JSON.parse('{{processes|safe}}');
                window.years_imported = JSON.parse('{{years_imported|safe}}');
                window.teams_processed = JSON.parse('{{teams_processed|safe}}');
                // use years_imported if no teams processed yet
                if (teams_processed.length == 0) {
                    window.teams_processed = years_imported;
                }
                window.stats_generated = JSON.parse('{{stats_generated|safe}}');
                window.recent_10 = JSON.parse('{{recent_10|safe}}');
                window.recent_10_min_time = new Date({{recent_10_min_time|safe}});
                window.recent_10_max_time = new Date({{recent_10_max_time|safe}});
                window.max_time_elapsed = {{recent_10_max_elapsed|safe}};
                window.error_rate = {{error_rate|safe}};
                window.team_data = {{team_data|safe}};
                window.max_hits = {{max_hits|safe}};
                window.max_hrs = {{max_hrs|safe}};
                window.min_hits = {{min_hits|safe}};
                window.min_hrs = {{min_hrs|safe}};
                // window.num_teams_array = {{num_teams_array|safe}};

                /* #### parameters #### */
                // overall progress - reuse window sizes as well
                window.grid_width = 120;
                window.grid_height = 310;
                window.bar_height = 30;
                window.bar_spacing = 10 + bar_height;
                window.op_trans = 1000; // overall progress bar transition time (ms)
                window.view_height = grid_height + 100;
                window.view_width = grid_width * processes.length + 150;

                // recent 10 completions
                window.recent_start_x = view_width + 25;

                window.svg_height = view_height * 2 + 50;
                window.svg_width = view_width * 2 + 25;
            }());
    </script>
    {% load static %}
    <script src="{% static 'scripts/baseball/dashboard_overall.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_recent.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_error_pie.js' %}"></script>
    <script src="{% static 'scripts/baseball/dashboard_leaders.js' %}"></script>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/project.html
{% include 'partials/header_baseball.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>PROJECT: Baseball Stats</h1>
    </div><br>
    {% load markdown_extras %}
    <div id="my_descriptions" class="d-flex justify-content-center">
        <div class="col-md-2"></div>
        <div class="col-md-8">
        <!--div class="highlight" kinda works-->
            {{ readme | markdown | safe }}
        </div>
        <div class="col-md-2">
    </div>
    <br>

{% include 'partials/footer_baseball.html' %}

baseball/templates/pages/viewStats.html
{% include 'partials/header_viewStats.html' %}
    <div id="my_title" class="d-flex justify-content-center">
        <h1>View Team Stats</h1>
    </div><br>

    {% load crispy_forms_tags %}
    <form id="view_stats" method="post" data-teams-url="{% url 'ajax_load_teams' %}" novalidate>
        {% csrf_token %}
        {{ form_view_stats.as_table }}
        <!--input type="submit" value="View Stats"-->
    </form>


    <div class="col-1">
        <div class="switch-toggle switch-3 switch-candy">
            <input id="batting" name="state-d" type="radio" value="batting" checked="checked" />
            <label class="stat_state" for="batting" onclick="">batting</label>

            <input id="pitching" name="state-d" type="radio" value="pitching" />
            <label class="stat_state" for="pitching" onclick="">pitching</label>

            <input id="fielding" name="state-d" type="radio" value="fielding" />
            <label class="stat_state" for="fielding" onclick="">fielding</label>

            <a></a>
        </div>
    </div>

    <div class="d-flex justify-content-center">
        <h3 id="select_header">2019 Batting Stats for ANA</h3>
    </div><br>
    <div id="table_div" class="d-flex justify-content-center">
        <table id="table_output" class="display" width="100%"></table><br>
    </div><br>
    <script>
    // for the teams drop-down dependency
    $("#id_year").change(function () {
        var url = $("#view_stats").attr("data-teams-url");  // get the url of the `load_teams` view
        var yearId = $(this).val();  // get selected YEAR
        //console.log(url);
        // initialize an AJAX request
        $.ajax({
            //async: true,
            url: url,  // set the url of the request (= localhost:8000/ajax/load-teams/)
            data: {
                'year': yearId  // add the year id to the GET parameters
            },
            success: function (data) {  // `data` is the return of the `load_teams` view function
                //console.log(data);
                $("#id_team").html(data);  // replace with the values retrieved
            }
        });
    });

    // get request for the DataTable stats
    $(document).ready(function() {
        window.col_types = {{col_types|safe}};

        // instantiate DataTable
        table_instantiate();
    });

    // new GET request call every time the team name is changed
    $("#id_team").change(function () {
        getURL = "/api/stat_results?format=datatables&year=" + $("#id_year").val()  +
            "&team=" + $("#id_team").val() + "&stats_table=" + $("input[name=state-d]:checked").val();
        //console.log(getURL);
        table.ajax.url(getURL).load();

        // update the header
        update_header();
    });

    // new GET request when stat type is toggled (batting, pitching, fielding)
    $(".switch-candy").change(function() {

        // destroy the table, then setup a new table
        table.destroy(true);
        var get_div = document.getElementById("table_div");
        var new_table = document.createElement("table");
        new_table.setAttribute("id", "table_output");
        new_table.setAttribute("class", "display");
        new_table.setAttribute("width", "100%");
        get_div.appendChild(new_table);

        // instantiate the table
        table_instantiate();

        //console.log("switch toggled");

        // update header
        update_header();
    });

    // function to instantiate DataTable
    function table_instantiate() {
        getURL = "/api/stat_results?format=datatables&year=" + $("#id_year").val() +
            "&team=" + $("#id_team").val() + "&stats_table=" + $("input[name=state-d]:checked").val();
        console.log(getURL);

        // instantiate the table
        table = $('#table_output').DataTable({
            "ajax": getURL,
            "columns": col_types[$("input[name=state-d]:checked").val()]['column_name'],
            "paging": false
        });

        // add the title to use for tool tip later
        $('#table_output thead tr th').each( function() {
            var sTitle;
            var nTds = $(this);
            var sTip = $(nTds[0]).text();
            //console.log(sTip);
            var sDesc = col_types[$("input[name=state-d]:checked").val()]['column_desc'][sTip];
            //console.log(sDesc);
            this.setAttribute('title', sDesc);
        });
    };

    // function to update header
    function update_header() {
        var stat_select = $("input[name=state-d]:checked").val();
        var first_letter = stat_select.charAt(0).toUpperCase();
        stat_select = first_letter + stat_select.slice(1); // skip first letter
        //console.log(stat_select);
        $("#select_header").text($("#id_year").val() + " " + stat_select + " Stats for " + $("#id_team").val());
    };
    </script>

{% include 'partials/footer_baseball.html' %}